# Generated by Django 5.1.4 on 2025-02-26 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('place', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('Confirmer', 'Confirmer'), ('Annuler', 'Annuler')], default='En attente', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointement', to='patient.patient')),
            ],
        ),
    ]
