# Generated by Django 5.1.4 on 2025-01-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointement',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointement',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
