# Generated by Django 5.1.4 on 2025-01-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointement', '0002_alter_appointement_date_alter_appointement_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
